pring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/dbbot?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
    jpa:
      hibernate.ddl-auto: update
      generate-ddl: true
      format_sql: true
      show-sql: false